package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbActionApi generated by hbm2java
 */
public class TbActionApi implements java.io.Serializable {

	private String eventId;
	private TbEvent tbEvent;
	private String tenantId;
	private String uri;
	private String method;
	private String basicAuthId;
	private String basicAuthPass;
	private String fieldName1;
	private String fieldValue1;
	private String fieldName2;
	private String fieldValue2;
	private String fieldName3;
	private String fieldValue3;
	private String fieldName4;
	private String fieldValue4;
	private String fieldName5;
	private String fieldValue5;
	private String fieldName6;
	private String fieldValue6;
	private String fieldName7;
	private String fieldValue7;
	private String fieldName8;
	private String fieldValue8;
	private String fieldName9;
	private String fieldValue9;
	private String fieldName10;
	private String fieldValue10;
	private String body;
	private String reserved01;
	private String reserved02;
	private String reserved03;

	public TbActionApi() {
	}

	public TbActionApi(TbEvent tbEvent, String uri, String method) {
		this.tbEvent = tbEvent;
		this.uri = uri;
		this.method = method;
	}

	public TbActionApi(TbEvent tbEvent, String tenantId, String uri, String method, String basicAuthId,
			String basicAuthPass, String fieldName1, String fieldValue1, String fieldName2, String fieldValue2,
			String fieldName3, String fieldValue3, String fieldName4, String fieldValue4, String fieldName5,
			String fieldValue5, String fieldName6, String fieldValue6, String fieldName7, String fieldValue7,
			String fieldName8, String fieldValue8, String fieldName9, String fieldValue9, String fieldName10,
			String fieldValue10, String body, String reserved01, String reserved02, String reserved03) {
		this.tbEvent = tbEvent;
		this.tenantId = tenantId;
		this.uri = uri;
		this.method = method;
		this.basicAuthId = basicAuthId;
		this.basicAuthPass = basicAuthPass;
		this.fieldName1 = fieldName1;
		this.fieldValue1 = fieldValue1;
		this.fieldName2 = fieldName2;
		this.fieldValue2 = fieldValue2;
		this.fieldName3 = fieldName3;
		this.fieldValue3 = fieldValue3;
		this.fieldName4 = fieldName4;
		this.fieldValue4 = fieldValue4;
		this.fieldName5 = fieldName5;
		this.fieldValue5 = fieldValue5;
		this.fieldName6 = fieldName6;
		this.fieldValue6 = fieldValue6;
		this.fieldName7 = fieldName7;
		this.fieldValue7 = fieldValue7;
		this.fieldName8 = fieldName8;
		this.fieldValue8 = fieldValue8;
		this.fieldName9 = fieldName9;
		this.fieldValue9 = fieldValue9;
		this.fieldName10 = fieldName10;
		this.fieldValue10 = fieldValue10;
		this.body = body;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
		this.reserved03 = reserved03;
	}

	public String getEventId() {
		return this.eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	public TbEvent getTbEvent() {
		return this.tbEvent;
	}

	public void setTbEvent(TbEvent tbEvent) {
		this.tbEvent = tbEvent;
	}

	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public String getBasicAuthId() {
		return this.basicAuthId;
	}

	public void setBasicAuthId(String basicAuthId) {
		this.basicAuthId = basicAuthId;
	}

	public String getBasicAuthPass() {
		return this.basicAuthPass;
	}

	public void setBasicAuthPass(String basicAuthPass) {
		this.basicAuthPass = basicAuthPass;
	}

	public String getFieldName1() {
		return this.fieldName1;
	}

	public void setFieldName1(String fieldName1) {
		this.fieldName1 = fieldName1;
	}

	public String getFieldValue1() {
		return this.fieldValue1;
	}

	public void setFieldValue1(String fieldValue1) {
		this.fieldValue1 = fieldValue1;
	}

	public String getFieldName2() {
		return this.fieldName2;
	}

	public void setFieldName2(String fieldName2) {
		this.fieldName2 = fieldName2;
	}

	public String getFieldValue2() {
		return this.fieldValue2;
	}

	public void setFieldValue2(String fieldValue2) {
		this.fieldValue2 = fieldValue2;
	}

	public String getFieldName3() {
		return this.fieldName3;
	}

	public void setFieldName3(String fieldName3) {
		this.fieldName3 = fieldName3;
	}

	public String getFieldValue3() {
		return this.fieldValue3;
	}

	public void setFieldValue3(String fieldValue3) {
		this.fieldValue3 = fieldValue3;
	}

	public String getFieldName4() {
		return this.fieldName4;
	}

	public void setFieldName4(String fieldName4) {
		this.fieldName4 = fieldName4;
	}

	public String getFieldValue4() {
		return this.fieldValue4;
	}

	public void setFieldValue4(String fieldValue4) {
		this.fieldValue4 = fieldValue4;
	}

	public String getFieldName5() {
		return this.fieldName5;
	}

	public void setFieldName5(String fieldName5) {
		this.fieldName5 = fieldName5;
	}

	public String getFieldValue5() {
		return this.fieldValue5;
	}

	public void setFieldValue5(String fieldValue5) {
		this.fieldValue5 = fieldValue5;
	}

	public String getFieldName6() {
		return this.fieldName6;
	}

	public void setFieldName6(String fieldName6) {
		this.fieldName6 = fieldName6;
	}

	public String getFieldValue6() {
		return this.fieldValue6;
	}

	public void setFieldValue6(String fieldValue6) {
		this.fieldValue6 = fieldValue6;
	}

	public String getFieldName7() {
		return this.fieldName7;
	}

	public void setFieldName7(String fieldName7) {
		this.fieldName7 = fieldName7;
	}

	public String getFieldValue7() {
		return this.fieldValue7;
	}

	public void setFieldValue7(String fieldValue7) {
		this.fieldValue7 = fieldValue7;
	}

	public String getFieldName8() {
		return this.fieldName8;
	}

	public void setFieldName8(String fieldName8) {
		this.fieldName8 = fieldName8;
	}

	public String getFieldValue8() {
		return this.fieldValue8;
	}

	public void setFieldValue8(String fieldValue8) {
		this.fieldValue8 = fieldValue8;
	}

	public String getFieldName9() {
		return this.fieldName9;
	}

	public void setFieldName9(String fieldName9) {
		this.fieldName9 = fieldName9;
	}

	public String getFieldValue9() {
		return this.fieldValue9;
	}

	public void setFieldValue9(String fieldValue9) {
		this.fieldValue9 = fieldValue9;
	}

	public String getFieldName10() {
		return this.fieldName10;
	}

	public void setFieldName10(String fieldName10) {
		this.fieldName10 = fieldName10;
	}

	public String getFieldValue10() {
		return this.fieldValue10;
	}

	public void setFieldValue10(String fieldValue10) {
		this.fieldValue10 = fieldValue10;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(String reserved02) {
		this.reserved02 = reserved02;
	}

	public String getReserved03() {
		return this.reserved03;
	}

	public void setReserved03(String reserved03) {
		this.reserved03 = reserved03;
	}

}
