package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbAccessCodePermissionId generated by hbm2java
 */
public class TbAccessCodePermissionId implements java.io.Serializable {

	private String resourceId;
	private String accessCode;

	public TbAccessCodePermissionId() {
	}

	public TbAccessCodePermissionId(String resourceId, String accessCode) {
		this.resourceId = resourceId;
		this.accessCode = accessCode;
	}

	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	public String getAccessCode() {
		return this.accessCode;
	}

	public void setAccessCode(String accessCode) {
		this.accessCode = accessCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbAccessCodePermissionId))
			return false;
		TbAccessCodePermissionId castOther = (TbAccessCodePermissionId) other;

		return ((this.getResourceId() == castOther.getResourceId()) || (this.getResourceId() != null
				&& castOther.getResourceId() != null && this.getResourceId().equals(castOther.getResourceId())))
				&& ((this.getAccessCode() == castOther.getAccessCode())
						|| (this.getAccessCode() != null && castOther.getAccessCode() != null
								&& this.getAccessCode().equals(castOther.getAccessCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getResourceId() == null ? 0 : this.getResourceId().hashCode());
		result = 37 * result + (getAccessCode() == null ? 0 : this.getAccessCode().hashCode());
		return result;
	}

}
