package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbAccessCodeResultId generated by hbm2java
 */
public class TbAccessCodeResultId implements java.io.Serializable {

	private String tenantId;
	private String userId;
	private int number;
	private String accessCode;
	private String accessCodeName;
	private String status;
	private String errMessage;

	public TbAccessCodeResultId() {
	}

	public TbAccessCodeResultId(String tenantId, String userId, int number, String accessCode, String status) {
		this.tenantId = tenantId;
		this.userId = userId;
		this.number = number;
		this.accessCode = accessCode;
		this.status = status;
	}

	public TbAccessCodeResultId(String tenantId, String userId, int number, String accessCode, String accessCodeName,
			String status, String errMessage) {
		this.tenantId = tenantId;
		this.userId = userId;
		this.number = number;
		this.accessCode = accessCode;
		this.accessCodeName = accessCodeName;
		this.status = status;
		this.errMessage = errMessage;
	}

	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public String getAccessCode() {
		return this.accessCode;
	}

	public void setAccessCode(String accessCode) {
		this.accessCode = accessCode;
	}

	public String getAccessCodeName() {
		return this.accessCodeName;
	}

	public void setAccessCodeName(String accessCodeName) {
		this.accessCodeName = accessCodeName;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getErrMessage() {
		return this.errMessage;
	}

	public void setErrMessage(String errMessage) {
		this.errMessage = errMessage;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbAccessCodeResultId))
			return false;
		TbAccessCodeResultId castOther = (TbAccessCodeResultId) other;

		return ((this.getTenantId() == castOther.getTenantId()) || (this.getTenantId() != null
				&& castOther.getTenantId() != null && this.getTenantId().equals(castOther.getTenantId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& (this.getNumber() == castOther.getNumber())
				&& ((this.getAccessCode() == castOther.getAccessCode()) || (this.getAccessCode() != null
						&& castOther.getAccessCode() != null && this.getAccessCode().equals(castOther.getAccessCode())))
				&& ((this.getAccessCodeName() == castOther.getAccessCodeName())
						|| (this.getAccessCodeName() != null && castOther.getAccessCodeName() != null
								&& this.getAccessCodeName().equals(castOther.getAccessCodeName())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())))
				&& ((this.getErrMessage() == castOther.getErrMessage())
						|| (this.getErrMessage() != null && castOther.getErrMessage() != null
								&& this.getErrMessage().equals(castOther.getErrMessage())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTenantId() == null ? 0 : this.getTenantId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + this.getNumber();
		result = 37 * result + (getAccessCode() == null ? 0 : this.getAccessCode().hashCode());
		result = 37 * result + (getAccessCodeName() == null ? 0 : this.getAccessCodeName().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		result = 37 * result + (getErrMessage() == null ? 0 : this.getErrMessage().hashCode());
		return result;
	}

}
