package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * TbAccessCodePermission generated by hbm2java
 */
public class TbAccessCodePermission implements java.io.Serializable {

	private TbAccessCodePermissionId id;
	private TbAccessCode tbAccessCode;
	private TbResourceId tbResourceId;
	private TbTenant tbTenant;
	private boolean readPermission;
	private boolean updatePermission;
	private Date addedDate;
	private Date modifiedDate;
	private String reserved01;
	private String reserved02;
	private String reserved03;

	public TbAccessCodePermission() {
	}

	public TbAccessCodePermission(TbAccessCodePermissionId id, TbAccessCode tbAccessCode, TbResourceId tbResourceId,
			boolean readPermission, boolean updatePermission, Date addedDate) {
		this.id = id;
		this.tbAccessCode = tbAccessCode;
		this.tbResourceId = tbResourceId;
		this.readPermission = readPermission;
		this.updatePermission = updatePermission;
		this.addedDate = addedDate;
	}

	public TbAccessCodePermission(TbAccessCodePermissionId id, TbAccessCode tbAccessCode, TbResourceId tbResourceId,
			boolean readPermission, boolean updatePermission, Date addedDate, Date modifiedDate, String reserved01,
			String reserved02, String reserved03) {
		this.id = id;
		this.tbAccessCode = tbAccessCode;
		this.tbResourceId = tbResourceId;
		this.readPermission = readPermission;
		this.updatePermission = updatePermission;
		this.addedDate = addedDate;
		this.modifiedDate = modifiedDate;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
		this.reserved03 = reserved03;
	}

	public TbAccessCodePermissionId getId() {
		return this.id;
	}

	public void setId(TbAccessCodePermissionId id) {
		this.id = id;
	}

	public TbAccessCode getTbAccessCode() {
		return this.tbAccessCode;
	}

	public void setTbAccessCode(TbAccessCode tbAccessCode) {
		this.tbAccessCode = tbAccessCode;
	}

	public TbResourceId getTbResourceId() {
		return this.tbResourceId;
	}

	public void setTbResourceId(TbResourceId tbResourceId) {
		this.tbResourceId = tbResourceId;
	}

	public TbTenant getTbTenant() {
		return this.tbTenant;
	}

	public void setTbTenant(TbTenant tbTenant) {
		this.tbTenant = tbTenant;
	}

	public boolean isReadPermission() {
		return this.readPermission;
	}

	public void setReadPermission(boolean readPermission) {
		this.readPermission = readPermission;
	}

	public boolean isUpdatePermission() {
		return this.updatePermission;
	}

	public void setUpdatePermission(boolean updatePermission) {
		this.updatePermission = updatePermission;
	}

	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(String reserved02) {
		this.reserved02 = reserved02;
	}

	public String getReserved03() {
		return this.reserved03;
	}

	public void setReserved03(String reserved03) {
		this.reserved03 = reserved03;
	}

}
