package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbAccessCodeResult generated by hbm2java
 */
public class TbAccessCodeResult implements java.io.Serializable {

	private TbAccessCodeResultId id;

	public TbAccessCodeResult() {
	}

	public TbAccessCodeResult(TbAccessCodeResultId id) {
		this.id = id;
	}

	public TbAccessCodeResultId getId() {
		return this.id;
	}

	public void setId(TbAccessCodeResultId id) {
		this.id = id;
	}

}
