package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbAccessCodeId generated by hbm2java
 */
public class TbAccessCodeId implements java.io.Serializable {

	private String tenantId;
	private String accessCode;

	public TbAccessCodeId() {
	}

	public TbAccessCodeId(String tenantId, String accessCode) {
		this.tenantId = tenantId;
		this.accessCode = accessCode;
	}

	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public String getAccessCode() {
		return this.accessCode;
	}

	public void setAccessCode(String accessCode) {
		this.accessCode = accessCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbAccessCodeId))
			return false;
		TbAccessCodeId castOther = (TbAccessCodeId) other;

		return ((this.getTenantId() == castOther.getTenantId()) || (this.getTenantId() != null
				&& castOther.getTenantId() != null && this.getTenantId().equals(castOther.getTenantId())))
				&& ((this.getAccessCode() == castOther.getAccessCode())
						|| (this.getAccessCode() != null && castOther.getAccessCode() != null
								&& this.getAccessCode().equals(castOther.getAccessCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTenantId() == null ? 0 : this.getTenantId().hashCode());
		result = 37 * result + (getAccessCode() == null ? 0 : this.getAccessCode().hashCode());
		return result;
	}

}
