package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbApiLog generated by hbm2java
 */
public class TbApiLog implements java.io.Serializable {

	private TbApiLogId id;

	public TbApiLog() {
	}

	public TbApiLog(TbApiLogId id) {
		this.id = id;
	}

	public TbApiLogId getId() {
		return this.id;
	}

	public void setId(TbApiLogId id) {
		this.id = id;
	}

}
