package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbChargingLogDaily generated by hbm2java
 */
public class TbChargingLogDaily implements java.io.Serializable {

	private TbChargingLogDailyId id;
	private int resourceRegistration;
	private int diskUsage;
	private int apiUsage;
	private int sslUsage;
	private int eventUsage;

	public TbChargingLogDaily() {
	}

	public TbChargingLogDaily(TbChargingLogDailyId id, int resourceRegistration, int diskUsage, int apiUsage,
			int sslUsage, int eventUsage) {
		this.id = id;
		this.resourceRegistration = resourceRegistration;
		this.diskUsage = diskUsage;
		this.apiUsage = apiUsage;
		this.sslUsage = sslUsage;
		this.eventUsage = eventUsage;
	}

	public TbChargingLogDailyId getId() {
		return this.id;
	}

	public void setId(TbChargingLogDailyId id) {
		this.id = id;
	}

	public int getResourceRegistration() {
		return this.resourceRegistration;
	}

	public void setResourceRegistration(int resourceRegistration) {
		this.resourceRegistration = resourceRegistration;
	}

	public int getDiskUsage() {
		return this.diskUsage;
	}

	public void setDiskUsage(int diskUsage) {
		this.diskUsage = diskUsage;
	}

	public int getApiUsage() {
		return this.apiUsage;
	}

	public void setApiUsage(int apiUsage) {
		this.apiUsage = apiUsage;
	}

	public int getSslUsage() {
		return this.sslUsage;
	}

	public void setSslUsage(int sslUsage) {
		this.sslUsage = sslUsage;
	}

	public int getEventUsage() {
		return this.eventUsage;
	}

	public void setEventUsage(int eventUsage) {
		this.eventUsage = eventUsage;
	}

}
