package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbChargingLogDailyId generated by hbm2java
 */
public class TbChargingLogDailyId implements java.io.Serializable {

	private String tenantId;
	private String date;

	public TbChargingLogDailyId() {
	}

	public TbChargingLogDailyId(String tenantId, String date) {
		this.tenantId = tenantId;
		this.date = date;
	}

	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbChargingLogDailyId))
			return false;
		TbChargingLogDailyId castOther = (TbChargingLogDailyId) other;

		return ((this.getTenantId() == castOther.getTenantId()) || (this.getTenantId() != null
				&& castOther.getTenantId() != null && this.getTenantId().equals(castOther.getTenantId())))
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTenantId() == null ? 0 : this.getTenantId().hashCode());
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		return result;
	}

}
