package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbDispersionPolce generated by hbm2java
 */
public class TbDispersionPolce implements java.io.Serializable {

	private TbDispersionPolceId id;
	private TbAccessCode tbAccessCode;
	private TbResourceId tbResourceId;
	private boolean flag;
	private String name;
	private String comment;
	private int recommendPeriod;
	private int calculationPeriod;
	private String reserved01;
	private String reserved02;
	private String reserved03;
	private Date addedDate;
	private Date modifiedDate;
	private Set tbRecommends = new HashSet(0);

	public TbDispersionPolce() {
	}

	public TbDispersionPolce(TbDispersionPolceId id, TbAccessCode tbAccessCode, TbResourceId tbResourceId, boolean flag,
			int recommendPeriod, int calculationPeriod, Date addedDate) {
		this.id = id;
		this.tbAccessCode = tbAccessCode;
		this.tbResourceId = tbResourceId;
		this.flag = flag;
		this.recommendPeriod = recommendPeriod;
		this.calculationPeriod = calculationPeriod;
		this.addedDate = addedDate;
	}

	public TbDispersionPolce(TbDispersionPolceId id, TbAccessCode tbAccessCode, TbResourceId tbResourceId, boolean flag,
			String name, String comment, int recommendPeriod, int calculationPeriod, String reserved01,
			String reserved02, String reserved03, Date addedDate, Date modifiedDate, Set tbRecommends) {
		this.id = id;
		this.tbAccessCode = tbAccessCode;
		this.tbResourceId = tbResourceId;
		this.flag = flag;
		this.name = name;
		this.comment = comment;
		this.recommendPeriod = recommendPeriod;
		this.calculationPeriod = calculationPeriod;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
		this.reserved03 = reserved03;
		this.addedDate = addedDate;
		this.modifiedDate = modifiedDate;
		this.tbRecommends = tbRecommends;
	}

	public TbDispersionPolceId getId() {
		return this.id;
	}

	public void setId(TbDispersionPolceId id) {
		this.id = id;
	}

	public TbAccessCode getTbAccessCode() {
		return this.tbAccessCode;
	}

	public void setTbAccessCode(TbAccessCode tbAccessCode) {
		this.tbAccessCode = tbAccessCode;
	}

	public TbResourceId getTbResourceId() {
		return this.tbResourceId;
	}

	public void setTbResourceId(TbResourceId tbResourceId) {
		this.tbResourceId = tbResourceId;
	}

	public boolean isFlag() {
		return this.flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public int getRecommendPeriod() {
		return this.recommendPeriod;
	}

	public void setRecommendPeriod(int recommendPeriod) {
		this.recommendPeriod = recommendPeriod;
	}

	public int getCalculationPeriod() {
		return this.calculationPeriod;
	}

	public void setCalculationPeriod(int calculationPeriod) {
		this.calculationPeriod = calculationPeriod;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(String reserved02) {
		this.reserved02 = reserved02;
	}

	public String getReserved03() {
		return this.reserved03;
	}

	public void setReserved03(String reserved03) {
		this.reserved03 = reserved03;
	}

	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public Set getTbRecommends() {
		return this.tbRecommends;
	}

	public void setTbRecommends(Set tbRecommends) {
		this.tbRecommends = tbRecommends;
	}

}
