package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbIpfilterUserRelationId generated by hbm2java
 */
public class TbIpfilterUserRelationId implements java.io.Serializable {

	private int ipfilterId;
	private String userId;
	private boolean flag;

	public TbIpfilterUserRelationId() {
	}

	public TbIpfilterUserRelationId(int ipfilterId, String userId, boolean flag) {
		this.ipfilterId = ipfilterId;
		this.userId = userId;
		this.flag = flag;
	}

	public int getIpfilterId() {
		return this.ipfilterId;
	}

	public void setIpfilterId(int ipfilterId) {
		this.ipfilterId = ipfilterId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean isFlag() {
		return this.flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbIpfilterUserRelationId))
			return false;
		TbIpfilterUserRelationId castOther = (TbIpfilterUserRelationId) other;

		return (this.getIpfilterId() == castOther.getIpfilterId())
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& (this.isFlag() == castOther.isFlag());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIpfilterId();
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (this.isFlag() ? 1 : 0);
		return result;
	}

}
