package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * TbIpfilterUserRelation generated by hbm2java
 */
public class TbIpfilterUserRelation implements java.io.Serializable {

	private TbIpfilterUserRelationId id;
	private TbIpfilterUser tbIpfilterUser;
	private TbUser tbUser;
	private String customerId;
	private String reserved01;
	private String reserved02;
	private String reserved03;
	private Date addedDate;
	private Date modifiedDate;

	public TbIpfilterUserRelation() {
	}

	public TbIpfilterUserRelation(TbIpfilterUserRelationId id, TbIpfilterUser tbIpfilterUser, TbUser tbUser,
			String customerId, Date addedDate) {
		this.id = id;
		this.tbIpfilterUser = tbIpfilterUser;
		this.tbUser = tbUser;
		this.customerId = customerId;
		this.addedDate = addedDate;
	}

	public TbIpfilterUserRelation(TbIpfilterUserRelationId id, TbIpfilterUser tbIpfilterUser, TbUser tbUser,
			String customerId, String reserved01, String reserved02, String reserved03, Date addedDate,
			Date modifiedDate) {
		this.id = id;
		this.tbIpfilterUser = tbIpfilterUser;
		this.tbUser = tbUser;
		this.customerId = customerId;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
		this.reserved03 = reserved03;
		this.addedDate = addedDate;
		this.modifiedDate = modifiedDate;
	}

	public TbIpfilterUserRelationId getId() {
		return this.id;
	}

	public void setId(TbIpfilterUserRelationId id) {
		this.id = id;
	}

	public TbIpfilterUser getTbIpfilterUser() {
		return this.tbIpfilterUser;
	}

	public void setTbIpfilterUser(TbIpfilterUser tbIpfilterUser) {
		this.tbIpfilterUser = tbIpfilterUser;
	}

	public TbUser getTbUser() {
		return this.tbUser;
	}

	public void setTbUser(TbUser tbUser) {
		this.tbUser = tbUser;
	}

	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(String reserved02) {
		this.reserved02 = reserved02;
	}

	public String getReserved03() {
		return this.reserved03;
	}

	public void setReserved03(String reserved03) {
		this.reserved03 = reserved03;
	}

	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
