package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * TbIpfilterAccesscodeRelation generated by hbm2java
 */
public class TbIpfilterAccesscodeRelation implements java.io.Serializable {

	private TbIpfilterAccesscodeRelationId id;
	private TbIpfilterAccesscode tbIpfilterAccesscode;
	private TbAccessCode tbAccessCode;
	private String reserved01;
	private String reserved02;
	private String reserved03;
	private Date addedDate;
	private Date modifiedDate;

	public TbIpfilterAccesscodeRelation() {
	}

	public TbIpfilterAccesscodeRelation(TbIpfilterAccesscodeRelationId id, TbIpfilterAccesscode tbIpfilterAccesscode,
			TbAccessCode tbAccessCode, Date addedDate) {
		this.id = id;
		this.tbIpfilterAccesscode = tbIpfilterAccesscode;
		this.tbAccessCode = tbAccessCode;
		this.addedDate = addedDate;
	}

	public TbIpfilterAccesscodeRelation(TbIpfilterAccesscodeRelationId id, TbIpfilterAccesscode tbIpfilterAccesscode,
			TbAccessCode tbAccessCode, String reserved01, String reserved02, String reserved03, Date addedDate,
			Date modifiedDate) {
		this.id = id;
		this.tbIpfilterAccesscode = tbIpfilterAccesscode;
		this.tbAccessCode = tbAccessCode;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
		this.reserved03 = reserved03;
		this.addedDate = addedDate;
		this.modifiedDate = modifiedDate;
	}

	public TbIpfilterAccesscodeRelationId getId() {
		return this.id;
	}

	public void setId(TbIpfilterAccesscodeRelationId id) {
		this.id = id;
	}

	public TbIpfilterAccesscode getTbIpfilterAccesscode() {
		return this.tbIpfilterAccesscode;
	}

	public void setTbIpfilterAccesscode(TbIpfilterAccesscode tbIpfilterAccesscode) {
		this.tbIpfilterAccesscode = tbIpfilterAccesscode;
	}

	public TbAccessCode getTbAccessCode() {
		return this.tbAccessCode;
	}

	public void setTbAccessCode(TbAccessCode tbAccessCode) {
		this.tbAccessCode = tbAccessCode;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(String reserved02) {
		this.reserved02 = reserved02;
	}

	public String getReserved03() {
		return this.reserved03;
	}

	public void setReserved03(String reserved03) {
		this.reserved03 = reserved03;
	}

	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
