package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbIpfilterUser generated by hbm2java
 */
public class TbIpfilterUser implements java.io.Serializable {

	private int ipfilterId;
	private Serializable ipaddressStart;
	private Serializable ipaddressEnd;
	private Serializable oldIpaddressStart;
	private Serializable oldIpaddressEnd;
	private String comment;
	private Boolean loginFlag;
	private String reserved01;
	private String reserved02;
	private String reserved03;
	private Date addedDate;
	private Date modifiedDate;
	private Boolean deleteFlag;
	private Set tbIpfilterUserRelations = new HashSet(0);

	public TbIpfilterUser() {
	}

	public TbIpfilterUser(int ipfilterId, Serializable ipaddressStart, Date addedDate) {
		this.ipfilterId = ipfilterId;
		this.ipaddressStart = ipaddressStart;
		this.addedDate = addedDate;
	}

	public TbIpfilterUser(int ipfilterId, Serializable ipaddressStart, Serializable ipaddressEnd,
			Serializable oldIpaddressStart, Serializable oldIpaddressEnd, String comment, Boolean loginFlag,
			String reserved01, String reserved02, String reserved03, Date addedDate, Date modifiedDate,
			Boolean deleteFlag, Set tbIpfilterUserRelations) {
		this.ipfilterId = ipfilterId;
		this.ipaddressStart = ipaddressStart;
		this.ipaddressEnd = ipaddressEnd;
		this.oldIpaddressStart = oldIpaddressStart;
		this.oldIpaddressEnd = oldIpaddressEnd;
		this.comment = comment;
		this.loginFlag = loginFlag;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
		this.reserved03 = reserved03;
		this.addedDate = addedDate;
		this.modifiedDate = modifiedDate;
		this.deleteFlag = deleteFlag;
		this.tbIpfilterUserRelations = tbIpfilterUserRelations;
	}

	public int getIpfilterId() {
		return this.ipfilterId;
	}

	public void setIpfilterId(int ipfilterId) {
		this.ipfilterId = ipfilterId;
	}

	public Serializable getIpaddressStart() {
		return this.ipaddressStart;
	}

	public void setIpaddressStart(Serializable ipaddressStart) {
		this.ipaddressStart = ipaddressStart;
	}

	public Serializable getIpaddressEnd() {
		return this.ipaddressEnd;
	}

	public void setIpaddressEnd(Serializable ipaddressEnd) {
		this.ipaddressEnd = ipaddressEnd;
	}

	public Serializable getOldIpaddressStart() {
		return this.oldIpaddressStart;
	}

	public void setOldIpaddressStart(Serializable oldIpaddressStart) {
		this.oldIpaddressStart = oldIpaddressStart;
	}

	public Serializable getOldIpaddressEnd() {
		return this.oldIpaddressEnd;
	}

	public void setOldIpaddressEnd(Serializable oldIpaddressEnd) {
		this.oldIpaddressEnd = oldIpaddressEnd;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Boolean getLoginFlag() {
		return this.loginFlag;
	}

	public void setLoginFlag(Boolean loginFlag) {
		this.loginFlag = loginFlag;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(String reserved02) {
		this.reserved02 = reserved02;
	}

	public String getReserved03() {
		return this.reserved03;
	}

	public void setReserved03(String reserved03) {
		this.reserved03 = reserved03;
	}

	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public Boolean getDeleteFlag() {
		return this.deleteFlag;
	}

	public void setDeleteFlag(Boolean deleteFlag) {
		this.deleteFlag = deleteFlag;
	}

	public Set getTbIpfilterUserRelations() {
		return this.tbIpfilterUserRelations;
	}

	public void setTbIpfilterUserRelations(Set tbIpfilterUserRelations) {
		this.tbIpfilterUserRelations = tbIpfilterUserRelations;
	}

}
