package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * TbOperationLogId generated by hbm2java
 */
public class TbOperationLogId implements java.io.Serializable {

	private Date date;
	private String tenantId;
	private String userId;
	private String userName;
	private String operationId;
	private String details;
	private String comment;

	public TbOperationLogId() {
	}

	public TbOperationLogId(String userId, String operationId, String details) {
		this.userId = userId;
		this.operationId = operationId;
		this.details = details;
	}

	public TbOperationLogId(Date date, String tenantId, String userId, String userName, String operationId,
			String details, String comment) {
		this.date = date;
		this.tenantId = tenantId;
		this.userId = userId;
		this.userName = userName;
		this.operationId = operationId;
		this.details = details;
		this.comment = comment;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getOperationId() {
		return this.operationId;
	}

	public void setOperationId(String operationId) {
		this.operationId = operationId;
	}

	public String getDetails() {
		return this.details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbOperationLogId))
			return false;
		TbOperationLogId castOther = (TbOperationLogId) other;

		return ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
				&& this.getDate().equals(castOther.getDate())))
				&& ((this.getTenantId() == castOther.getTenantId()) || (this.getTenantId() != null
						&& castOther.getTenantId() != null && this.getTenantId().equals(castOther.getTenantId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null
						&& castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
				&& ((this.getOperationId() == castOther.getOperationId())
						|| (this.getOperationId() != null && castOther.getOperationId() != null
								&& this.getOperationId().equals(castOther.getOperationId())))
				&& ((this.getDetails() == castOther.getDetails()) || (this.getDetails() != null
						&& castOther.getDetails() != null && this.getDetails().equals(castOther.getDetails())))
				&& ((this.getComment() == castOther.getComment()) || (this.getComment() != null
						&& castOther.getComment() != null && this.getComment().equals(castOther.getComment())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getTenantId() == null ? 0 : this.getTenantId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
		result = 37 * result + (getOperationId() == null ? 0 : this.getOperationId().hashCode());
		result = 37 * result + (getDetails() == null ? 0 : this.getDetails().hashCode());
		result = 37 * result + (getComment() == null ? 0 : this.getComment().hashCode());
		return result;
	}

}
