package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbOperationLog generated by hbm2java
 */
public class TbOperationLog implements java.io.Serializable {

	private TbOperationLogId id;

	public TbOperationLog() {
	}

	public TbOperationLog(TbOperationLogId id) {
		this.id = id;
	}

	public TbOperationLogId getId() {
		return this.id;
	}

	public void setId(TbOperationLogId id) {
		this.id = id;
	}

}
