package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbRecommendId generated by hbm2java
 */
public class TbRecommendId implements java.io.Serializable {

	private String tenantId;
	private int dispersionPolceType;
	private int recommendDisp;

	public TbRecommendId() {
	}

	public TbRecommendId(String tenantId, int dispersionPolceType, int recommendDisp) {
		this.tenantId = tenantId;
		this.dispersionPolceType = dispersionPolceType;
		this.recommendDisp = recommendDisp;
	}

	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public int getDispersionPolceType() {
		return this.dispersionPolceType;
	}

	public void setDispersionPolceType(int dispersionPolceType) {
		this.dispersionPolceType = dispersionPolceType;
	}

	public int getRecommendDisp() {
		return this.recommendDisp;
	}

	public void setRecommendDisp(int recommendDisp) {
		this.recommendDisp = recommendDisp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbRecommendId))
			return false;
		TbRecommendId castOther = (TbRecommendId) other;

		return ((this.getTenantId() == castOther.getTenantId()) || (this.getTenantId() != null
				&& castOther.getTenantId() != null && this.getTenantId().equals(castOther.getTenantId())))
				&& (this.getDispersionPolceType() == castOther.getDispersionPolceType())
				&& (this.getRecommendDisp() == castOther.getRecommendDisp());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getTenantId() == null ? 0 : this.getTenantId().hashCode());
		result = 37 * result + this.getDispersionPolceType();
		result = 37 * result + this.getRecommendDisp();
		return result;
	}

}
