package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TbResourceDataDbServer generated by hbm2java
 */
public class TbResourceDataDbServer implements java.io.Serializable {

	private int dbServerId;
	private String hostname;
	private Boolean useDbServerFlag;
	private Set tbTenantCommons = new HashSet(0);

	public TbResourceDataDbServer() {
	}

	public TbResourceDataDbServer(int dbServerId) {
		this.dbServerId = dbServerId;
	}

	public TbResourceDataDbServer(int dbServerId, String hostname, Boolean useDbServerFlag, Set tbTenantCommons) {
		this.dbServerId = dbServerId;
		this.hostname = hostname;
		this.useDbServerFlag = useDbServerFlag;
		this.tbTenantCommons = tbTenantCommons;
	}

	public int getDbServerId() {
		return this.dbServerId;
	}

	public void setDbServerId(int dbServerId) {
		this.dbServerId = dbServerId;
	}

	public String getHostname() {
		return this.hostname;
	}

	public void setHostname(String hostname) {
		this.hostname = hostname;
	}

	public Boolean getUseDbServerFlag() {
		return this.useDbServerFlag;
	}

	public void setUseDbServerFlag(Boolean useDbServerFlag) {
		this.useDbServerFlag = useDbServerFlag;
	}

	public Set getTbTenantCommons() {
		return this.tbTenantCommons;
	}

	public void setTbTenantCommons(Set tbTenantCommons) {
		this.tbTenantCommons = tbTenantCommons;
	}

}
