package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * TbResource generated by hbm2java
 */
public class TbResource implements java.io.Serializable {

	private String resourceId;
	private TbResourceId tbResourceId;
	private TbTenant tbTenant;
	private String resourceName;
	private String resourcePath;
	private int dataFormat;
	private String comment;
	private int dbServerId;
	private String databaseName;
	private String collectionName;
	private Date resourceDataUpdatedDate;
	private int resourceClass;
	private Integer retentionPeriod;
	private String reserved01;
	private String reserved02;
	private String reserved03;
	private Date addedDate;
	private Date modifiedDate;

	public TbResource() {
	}

	public TbResource(TbResourceId tbResourceId, TbTenant tbTenant, String resourcePath, int dataFormat, int dbServerId,
			String databaseName, String collectionName, int resourceClass, Date addedDate) {
		this.tbResourceId = tbResourceId;
		this.tbTenant = tbTenant;
		this.resourcePath = resourcePath;
		this.dataFormat = dataFormat;
		this.dbServerId = dbServerId;
		this.databaseName = databaseName;
		this.collectionName = collectionName;
		this.resourceClass = resourceClass;
		this.addedDate = addedDate;
	}

	public TbResource(TbResourceId tbResourceId, TbTenant tbTenant, String resourceName, String resourcePath,
			int dataFormat, String comment, int dbServerId, String databaseName, String collectionName,
			Date resourceDataUpdatedDate, int resourceClass, Integer retentionPeriod, String reserved01,
			String reserved02, String reserved03, Date addedDate, Date modifiedDate) {
		this.tbResourceId = tbResourceId;
		this.tbTenant = tbTenant;
		this.resourceName = resourceName;
		this.resourcePath = resourcePath;
		this.dataFormat = dataFormat;
		this.comment = comment;
		this.dbServerId = dbServerId;
		this.databaseName = databaseName;
		this.collectionName = collectionName;
		this.resourceDataUpdatedDate = resourceDataUpdatedDate;
		this.resourceClass = resourceClass;
		this.retentionPeriod = retentionPeriod;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
		this.reserved03 = reserved03;
		this.addedDate = addedDate;
		this.modifiedDate = modifiedDate;
	}

	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	public TbResourceId getTbResourceId() {
		return this.tbResourceId;
	}

	public void setTbResourceId(TbResourceId tbResourceId) {
		this.tbResourceId = tbResourceId;
	}

	public TbTenant getTbTenant() {
		return this.tbTenant;
	}

	public void setTbTenant(TbTenant tbTenant) {
		this.tbTenant = tbTenant;
	}

	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	public String getResourcePath() {
		return this.resourcePath;
	}

	public void setResourcePath(String resourcePath) {
		this.resourcePath = resourcePath;
	}

	public int getDataFormat() {
		return this.dataFormat;
	}

	public void setDataFormat(int dataFormat) {
		this.dataFormat = dataFormat;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public int getDbServerId() {
		return this.dbServerId;
	}

	public void setDbServerId(int dbServerId) {
		this.dbServerId = dbServerId;
	}

	public String getDatabaseName() {
		return this.databaseName;
	}

	public void setDatabaseName(String databaseName) {
		this.databaseName = databaseName;
	}

	public String getCollectionName() {
		return this.collectionName;
	}

	public void setCollectionName(String collectionName) {
		this.collectionName = collectionName;
	}

	public Date getResourceDataUpdatedDate() {
		return this.resourceDataUpdatedDate;
	}

	public void setResourceDataUpdatedDate(Date resourceDataUpdatedDate) {
		this.resourceDataUpdatedDate = resourceDataUpdatedDate;
	}

	public int getResourceClass() {
		return this.resourceClass;
	}

	public void setResourceClass(int resourceClass) {
		this.resourceClass = resourceClass;
	}

	public Integer getRetentionPeriod() {
		return this.retentionPeriod;
	}

	public void setRetentionPeriod(Integer retentionPeriod) {
		this.retentionPeriod = retentionPeriod;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(String reserved02) {
		this.reserved02 = reserved02;
	}

	public String getReserved03() {
		return this.reserved03;
	}

	public void setReserved03(String reserved03) {
		this.reserved03 = reserved03;
	}

	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
