package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbResourceModifyStatus generated by hbm2java
 */
public class TbResourceModifyStatus implements java.io.Serializable {

	private TbResourceModifyStatusId id;

	public TbResourceModifyStatus() {
	}

	public TbResourceModifyStatus(TbResourceModifyStatusId id) {
		this.id = id;
	}

	public TbResourceModifyStatusId getId() {
		return this.id;
	}

	public void setId(TbResourceModifyStatusId id) {
		this.id = id;
	}

}
