package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbResourceResult generated by hbm2java
 */
public class TbResourceResult implements java.io.Serializable {

	private TbResourceResultId id;

	public TbResourceResult() {
	}

	public TbResourceResult(TbResourceResultId id) {
		this.id = id;
	}

	public TbResourceResultId getId() {
		return this.id;
	}

	public void setId(TbResourceResultId id) {
		this.id = id;
	}

}
