package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TbRecommend generated by hbm2java
 */
public class TbRecommend implements java.io.Serializable {

	private TbRecommendId id;
	private TbDispersionPolce tbDispersionPolce;
	private TbAccessCode tbAccessCode;
	private TbResourceId tbResourceId;
	private boolean flag;
	private String measureType;
	private Long onNumericValue;
	private BigDecimal onFloatValue;
	private Integer onNumericCondition;
	private String onStringValue;
	private Integer onStringCondition;
	private String onParameter;
	private Long offNumericValue;
	private BigDecimal offFloatValue;
	private Integer offNumericCondition;
	private String offStringValue;
	private Integer offStringCondition;
	private String offParameter;
	private String reserved01;
	private String reserved02;
	private String reserved03;
	private Date addedDate;
	private Date modifiedDate;

	public TbRecommend() {
	}

	public TbRecommend(TbRecommendId id, TbDispersionPolce tbDispersionPolce, TbAccessCode tbAccessCode,
			TbResourceId tbResourceId, boolean flag, Date addedDate) {
		this.id = id;
		this.tbDispersionPolce = tbDispersionPolce;
		this.tbAccessCode = tbAccessCode;
		this.tbResourceId = tbResourceId;
		this.flag = flag;
		this.addedDate = addedDate;
	}

	public TbRecommend(TbRecommendId id, TbDispersionPolce tbDispersionPolce, TbAccessCode tbAccessCode,
			TbResourceId tbResourceId, boolean flag, String measureType, Long onNumericValue, BigDecimal onFloatValue,
			Integer onNumericCondition, String onStringValue, Integer onStringCondition, String onParameter,
			Long offNumericValue, BigDecimal offFloatValue, Integer offNumericCondition, String offStringValue,
			Integer offStringCondition, String offParameter, String reserved01, String reserved02, String reserved03,
			Date addedDate, Date modifiedDate) {
		this.id = id;
		this.tbDispersionPolce = tbDispersionPolce;
		this.tbAccessCode = tbAccessCode;
		this.tbResourceId = tbResourceId;
		this.flag = flag;
		this.measureType = measureType;
		this.onNumericValue = onNumericValue;
		this.onFloatValue = onFloatValue;
		this.onNumericCondition = onNumericCondition;
		this.onStringValue = onStringValue;
		this.onStringCondition = onStringCondition;
		this.onParameter = onParameter;
		this.offNumericValue = offNumericValue;
		this.offFloatValue = offFloatValue;
		this.offNumericCondition = offNumericCondition;
		this.offStringValue = offStringValue;
		this.offStringCondition = offStringCondition;
		this.offParameter = offParameter;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
		this.reserved03 = reserved03;
		this.addedDate = addedDate;
		this.modifiedDate = modifiedDate;
	}

	public TbRecommendId getId() {
		return this.id;
	}

	public void setId(TbRecommendId id) {
		this.id = id;
	}

	public TbDispersionPolce getTbDispersionPolce() {
		return this.tbDispersionPolce;
	}

	public void setTbDispersionPolce(TbDispersionPolce tbDispersionPolce) {
		this.tbDispersionPolce = tbDispersionPolce;
	}

	public TbAccessCode getTbAccessCode() {
		return this.tbAccessCode;
	}

	public void setTbAccessCode(TbAccessCode tbAccessCode) {
		this.tbAccessCode = tbAccessCode;
	}

	public TbResourceId getTbResourceId() {
		return this.tbResourceId;
	}

	public void setTbResourceId(TbResourceId tbResourceId) {
		this.tbResourceId = tbResourceId;
	}

	public boolean isFlag() {
		return this.flag;
	}

	public void setFlag(boolean flag) {
		this.flag = flag;
	}

	public String getMeasureType() {
		return this.measureType;
	}

	public void setMeasureType(String measureType) {
		this.measureType = measureType;
	}

	public Long getOnNumericValue() {
		return this.onNumericValue;
	}

	public void setOnNumericValue(Long onNumericValue) {
		this.onNumericValue = onNumericValue;
	}

	public BigDecimal getOnFloatValue() {
		return this.onFloatValue;
	}

	public void setOnFloatValue(BigDecimal onFloatValue) {
		this.onFloatValue = onFloatValue;
	}

	public Integer getOnNumericCondition() {
		return this.onNumericCondition;
	}

	public void setOnNumericCondition(Integer onNumericCondition) {
		this.onNumericCondition = onNumericCondition;
	}

	public String getOnStringValue() {
		return this.onStringValue;
	}

	public void setOnStringValue(String onStringValue) {
		this.onStringValue = onStringValue;
	}

	public Integer getOnStringCondition() {
		return this.onStringCondition;
	}

	public void setOnStringCondition(Integer onStringCondition) {
		this.onStringCondition = onStringCondition;
	}

	public String getOnParameter() {
		return this.onParameter;
	}

	public void setOnParameter(String onParameter) {
		this.onParameter = onParameter;
	}

	public Long getOffNumericValue() {
		return this.offNumericValue;
	}

	public void setOffNumericValue(Long offNumericValue) {
		this.offNumericValue = offNumericValue;
	}

	public BigDecimal getOffFloatValue() {
		return this.offFloatValue;
	}

	public void setOffFloatValue(BigDecimal offFloatValue) {
		this.offFloatValue = offFloatValue;
	}

	public Integer getOffNumericCondition() {
		return this.offNumericCondition;
	}

	public void setOffNumericCondition(Integer offNumericCondition) {
		this.offNumericCondition = offNumericCondition;
	}

	public String getOffStringValue() {
		return this.offStringValue;
	}

	public void setOffStringValue(String offStringValue) {
		this.offStringValue = offStringValue;
	}

	public Integer getOffStringCondition() {
		return this.offStringCondition;
	}

	public void setOffStringCondition(Integer offStringCondition) {
		this.offStringCondition = offStringCondition;
	}

	public String getOffParameter() {
		return this.offParameter;
	}

	public void setOffParameter(String offParameter) {
		this.offParameter = offParameter;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(String reserved02) {
		this.reserved02 = reserved02;
	}

	public String getReserved03() {
		return this.reserved03;
	}

	public void setReserved03(String reserved03) {
		this.reserved03 = reserved03;
	}

	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
