package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * TbStorageAmount generated by hbm2java
 */
public class TbStorageAmount implements java.io.Serializable {

	private String resourceId;
	private TbResourceId tbResourceId;
	private long diskUsage;
	private Date date;

	public TbStorageAmount() {
	}

	public TbStorageAmount(TbResourceId tbResourceId, long diskUsage, Date date) {
		this.tbResourceId = tbResourceId;
		this.diskUsage = diskUsage;
		this.date = date;
	}

	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	public TbResourceId getTbResourceId() {
		return this.tbResourceId;
	}

	public void setTbResourceId(TbResourceId tbResourceId) {
		this.tbResourceId = tbResourceId;
	}

	public long getDiskUsage() {
		return this.diskUsage;
	}

	public void setDiskUsage(long diskUsage) {
		this.diskUsage = diskUsage;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
