package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbTargetResource generated by hbm2java
 */
public class TbTargetResource implements java.io.Serializable {

	private TbTargetResourceId id;
	private TbEvent tbEvent;
	private TbAccessCode tbAccessCode;
	private TbResourceId tbResourceId;
	private String notificationLocation;
	private String awakeLocation;
	private String notificationPathType;
	private String awakePathType;
	private String reserved01;
	private String reserved02;
	private String reserved03;

	public TbTargetResource() {
	}

	public TbTargetResource(TbTargetResourceId id, TbEvent tbEvent, TbAccessCode tbAccessCode,
			TbResourceId tbResourceId) {
		this.id = id;
		this.tbEvent = tbEvent;
		this.tbAccessCode = tbAccessCode;
		this.tbResourceId = tbResourceId;
	}

	public TbTargetResource(TbTargetResourceId id, TbEvent tbEvent, TbAccessCode tbAccessCode,
			TbResourceId tbResourceId, String notificationLocation, String awakeLocation, String notificationPathType,
			String awakePathType, String reserved01, String reserved02, String reserved03) {
		this.id = id;
		this.tbEvent = tbEvent;
		this.tbAccessCode = tbAccessCode;
		this.tbResourceId = tbResourceId;
		this.notificationLocation = notificationLocation;
		this.awakeLocation = awakeLocation;
		this.notificationPathType = notificationPathType;
		this.awakePathType = awakePathType;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
		this.reserved03 = reserved03;
	}

	public TbTargetResourceId getId() {
		return this.id;
	}

	public void setId(TbTargetResourceId id) {
		this.id = id;
	}

	public TbEvent getTbEvent() {
		return this.tbEvent;
	}

	public void setTbEvent(TbEvent tbEvent) {
		this.tbEvent = tbEvent;
	}

	public TbAccessCode getTbAccessCode() {
		return this.tbAccessCode;
	}

	public void setTbAccessCode(TbAccessCode tbAccessCode) {
		this.tbAccessCode = tbAccessCode;
	}

	public TbResourceId getTbResourceId() {
		return this.tbResourceId;
	}

	public void setTbResourceId(TbResourceId tbResourceId) {
		this.tbResourceId = tbResourceId;
	}

	public String getNotificationLocation() {
		return this.notificationLocation;
	}

	public void setNotificationLocation(String notificationLocation) {
		this.notificationLocation = notificationLocation;
	}

	public String getAwakeLocation() {
		return this.awakeLocation;
	}

	public void setAwakeLocation(String awakeLocation) {
		this.awakeLocation = awakeLocation;
	}

	public String getNotificationPathType() {
		return this.notificationPathType;
	}

	public void setNotificationPathType(String notificationPathType) {
		this.notificationPathType = notificationPathType;
	}

	public String getAwakePathType() {
		return this.awakePathType;
	}

	public void setAwakePathType(String awakePathType) {
		this.awakePathType = awakePathType;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(String reserved02) {
		this.reserved02 = reserved02;
	}

	public String getReserved03() {
		return this.reserved03;
	}

	public void setReserved03(String reserved03) {
		this.reserved03 = reserved03;
	}

}
