package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * TbTableManagement generated by hbm2java
 */
public class TbTableManagement implements java.io.Serializable {

	private String tableName;
	private Date updateDate;

	public TbTableManagement() {
	}

	public TbTableManagement(String tableName) {
		this.tableName = tableName;
	}

	public TbTableManagement(String tableName, Date updateDate) {
		this.tableName = tableName;
		this.updateDate = updateDate;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
