package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbTargetResourceId generated by hbm2java
 */
public class TbTargetResourceId implements java.io.Serializable {

	private String eventId;
	private String resourceId;

	public TbTargetResourceId() {
	}

	public TbTargetResourceId(String eventId, String resourceId) {
		this.eventId = eventId;
		this.resourceId = resourceId;
	}

	public String getEventId() {
		return this.eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbTargetResourceId))
			return false;
		TbTargetResourceId castOther = (TbTargetResourceId) other;

		return ((this.getEventId() == castOther.getEventId()) || (this.getEventId() != null
				&& castOther.getEventId() != null && this.getEventId().equals(castOther.getEventId())))
				&& ((this.getResourceId() == castOther.getResourceId())
						|| (this.getResourceId() != null && castOther.getResourceId() != null
								&& this.getResourceId().equals(castOther.getResourceId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEventId() == null ? 0 : this.getEventId().hashCode());
		result = 37 * result + (getResourceId() == null ? 0 : this.getResourceId().hashCode());
		return result;
	}

}
