package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbTenant generated by hbm2java
 */
public class TbTenant implements java.io.Serializable {

	private String tenantId;
	private TbManagementDataDbServer tbManagementDataDbServer;
	private TbCustomer tbCustomer;
	private String tenantName;
	private String selectionScreenComment;
	private String comment;
	private String safaiaId;
	private String accountingId;
	private int serviceType;
	private Date serviceTypeModifiedDate;
	private Integer freeApiSize;
	private Integer freeStorageSize;
	private boolean enhancingSupport;
	private Date accountStartDate;
	private Date accountEndDate;
	private String reserved01;
	private String reserved02;
	private String reserved03;
	private Date addedDate;
	private Date modifiedDate;
	private Set tbAccessCodes = new HashSet(0);
	private Set tbUsers = new HashSet(0);
	private Set tbEvents = new HashSet(0);
	private TbTenantCommon tbTenantCommon;
	private Set tbResources = new HashSet(0);

	public TbTenant() {
	}

	public TbTenant(String tenantId, TbManagementDataDbServer tbManagementDataDbServer, TbCustomer tbCustomer,
			String tenantName, String accountingId, int serviceType, boolean enhancingSupport, Date addedDate) {
		this.tenantId = tenantId;
		this.tbManagementDataDbServer = tbManagementDataDbServer;
		this.tbCustomer = tbCustomer;
		this.tenantName = tenantName;
		this.accountingId = accountingId;
		this.serviceType = serviceType;
		this.enhancingSupport = enhancingSupport;
		this.addedDate = addedDate;
	}

	public TbTenant(String tenantId, TbManagementDataDbServer tbManagementDataDbServer, TbCustomer tbCustomer,
			String tenantName, String selectionScreenComment, String comment, String safaiaId, String accountingId,
			int serviceType, Date serviceTypeModifiedDate, Integer freeApiSize, Integer freeStorageSize,
			boolean enhancingSupport, Date accountStartDate, Date accountEndDate, String reserved01, String reserved02,
			String reserved03, Date addedDate, Date modifiedDate, Set tbAccessCodes, Set tbUsers, Set tbEvents,
			TbTenantCommon tbTenantCommon, Set tbResources) {
		this.tenantId = tenantId;
		this.tbManagementDataDbServer = tbManagementDataDbServer;
		this.tbCustomer = tbCustomer;
		this.tenantName = tenantName;
		this.selectionScreenComment = selectionScreenComment;
		this.comment = comment;
		this.safaiaId = safaiaId;
		this.accountingId = accountingId;
		this.serviceType = serviceType;
		this.serviceTypeModifiedDate = serviceTypeModifiedDate;
		this.freeApiSize = freeApiSize;
		this.freeStorageSize = freeStorageSize;
		this.enhancingSupport = enhancingSupport;
		this.accountStartDate = accountStartDate;
		this.accountEndDate = accountEndDate;
		this.reserved01 = reserved01;
		this.reserved02 = reserved02;
		this.reserved03 = reserved03;
		this.addedDate = addedDate;
		this.modifiedDate = modifiedDate;
		this.tbAccessCodes = tbAccessCodes;
		this.tbUsers = tbUsers;
		this.tbEvents = tbEvents;
		this.tbTenantCommon = tbTenantCommon;
		this.tbResources = tbResources;
	}

	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public TbManagementDataDbServer getTbManagementDataDbServer() {
		return this.tbManagementDataDbServer;
	}

	public void setTbManagementDataDbServer(TbManagementDataDbServer tbManagementDataDbServer) {
		this.tbManagementDataDbServer = tbManagementDataDbServer;
	}

	public TbCustomer getTbCustomer() {
		return this.tbCustomer;
	}

	public void setTbCustomer(TbCustomer tbCustomer) {
		this.tbCustomer = tbCustomer;
	}

	public String getTenantName() {
		return this.tenantName;
	}

	public void setTenantName(String tenantName) {
		this.tenantName = tenantName;
	}

	public String getSelectionScreenComment() {
		return this.selectionScreenComment;
	}

	public void setSelectionScreenComment(String selectionScreenComment) {
		this.selectionScreenComment = selectionScreenComment;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getSafaiaId() {
		return this.safaiaId;
	}

	public void setSafaiaId(String safaiaId) {
		this.safaiaId = safaiaId;
	}

	public String getAccountingId() {
		return this.accountingId;
	}

	public void setAccountingId(String accountingId) {
		this.accountingId = accountingId;
	}

	public int getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(int serviceType) {
		this.serviceType = serviceType;
	}

	public Date getServiceTypeModifiedDate() {
		return this.serviceTypeModifiedDate;
	}

	public void setServiceTypeModifiedDate(Date serviceTypeModifiedDate) {
		this.serviceTypeModifiedDate = serviceTypeModifiedDate;
	}

	public Integer getFreeApiSize() {
		return this.freeApiSize;
	}

	public void setFreeApiSize(Integer freeApiSize) {
		this.freeApiSize = freeApiSize;
	}

	public Integer getFreeStorageSize() {
		return this.freeStorageSize;
	}

	public void setFreeStorageSize(Integer freeStorageSize) {
		this.freeStorageSize = freeStorageSize;
	}

	public boolean isEnhancingSupport() {
		return this.enhancingSupport;
	}

	public void setEnhancingSupport(boolean enhancingSupport) {
		this.enhancingSupport = enhancingSupport;
	}

	public Date getAccountStartDate() {
		return this.accountStartDate;
	}

	public void setAccountStartDate(Date accountStartDate) {
		this.accountStartDate = accountStartDate;
	}

	public Date getAccountEndDate() {
		return this.accountEndDate;
	}

	public void setAccountEndDate(Date accountEndDate) {
		this.accountEndDate = accountEndDate;
	}

	public String getReserved01() {
		return this.reserved01;
	}

	public void setReserved01(String reserved01) {
		this.reserved01 = reserved01;
	}

	public String getReserved02() {
		return this.reserved02;
	}

	public void setReserved02(String reserved02) {
		this.reserved02 = reserved02;
	}

	public String getReserved03() {
		return this.reserved03;
	}

	public void setReserved03(String reserved03) {
		this.reserved03 = reserved03;
	}

	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public Set getTbAccessCodes() {
		return this.tbAccessCodes;
	}

	public void setTbAccessCodes(Set tbAccessCodes) {
		this.tbAccessCodes = tbAccessCodes;
	}

	public Set getTbUsers() {
		return this.tbUsers;
	}

	public void setTbUsers(Set tbUsers) {
		this.tbUsers = tbUsers;
	}

	public Set getTbEvents() {
		return this.tbEvents;
	}

	public void setTbEvents(Set tbEvents) {
		this.tbEvents = tbEvents;
	}

	public TbTenantCommon getTbTenantCommon() {
		return this.tbTenantCommon;
	}

	public void setTbTenantCommon(TbTenantCommon tbTenantCommon) {
		this.tbTenantCommon = tbTenantCommon;
	}

	public Set getTbResources() {
		return this.tbResources;
	}

	public void setTbResources(Set tbResources) {
		this.tbResources = tbResources;
	}

}
