package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

/**
 * TbVersion generated by hbm2java
 */
public class TbVersion implements java.io.Serializable {

	private TbVersionId id;

	public TbVersion() {
	}

	public TbVersion(TbVersionId id) {
		this.id = id;
	}

	public TbVersionId getId() {
		return this.id;
	}

	public void setId(TbVersionId id) {
		this.id = id;
	}

}
