package com.yaotao.rest.tb;
// Generated 2016-1-2 22:34:23 by Hibernate Tools 3.6.0.Final

import java.util.Date;

/**
 * TbVersionId generated by hbm2java
 */
public class TbVersionId implements java.io.Serializable {

	private String version;
	private Date addedDate;

	public TbVersionId() {
	}

	public TbVersionId(String version, Date addedDate) {
		this.version = version;
		this.addedDate = addedDate;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TbVersionId))
			return false;
		TbVersionId castOther = (TbVersionId) other;

		return ((this.getVersion() == castOther.getVersion()) || (this.getVersion() != null
				&& castOther.getVersion() != null && this.getVersion().equals(castOther.getVersion())))
				&& ((this.getAddedDate() == castOther.getAddedDate()) || (this.getAddedDate() != null
						&& castOther.getAddedDate() != null && this.getAddedDate().equals(castOther.getAddedDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result + (getAddedDate() == null ? 0 : this.getAddedDate().hashCode());
		return result;
	}

}
